name: Laravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Migrate an Scheme
      run: php artisan migrate
