name: Laravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Generate key
      run: |
        ls
        cd /
        pwd
    - name: Migrate an Scheme
      run: |
        chmod +x artisan
        php artisan migrate
