name: Laravel CI/CD

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Navigate to project directory
        run: pwd;cd ..;pwd;

      - name: Install Composer dependencies
        run: composer install

      - name: Run database migrations
        run: php artisan migrate --force