name: Laravel

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./../../DismacAPI

    steps:
    - name: Generate key
      run: |
        ls
        pwd
